name: Trigger Action from Build Release

on:
  repository_dispatch:
    types: [trigger-action]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print received payload
        run: echo "Received ${{ github.event.client_payload.version }} from Build Release"

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and Release with Gradle
        run: |
          ./gradlew build-all -PrbapiVersion=${{ github.event.client_payload.version }}
          
